var heroes = {
    "lu":{
        "name":"Lu",
        "halo":40,
        "halomax":40,
        "power":"shadows",
        "powerattack":2,
        "weakness":"thunder",
        "position":{
            "world":"",
            "region":"",
            "scene":"",
            "step":"s2"
        }
    },
    "sarah":{
        "name":"Sarah",
        "halo":40,
        "halomax":40,
        "power":"ice",
        "powerattack":2,
        "weakness":"fire",
        "position":{
            "world":"",
            "region":"",
            "scene":"",
            "step":"s3"
        }
    },
    "arthur":{
        "name":"Arthur",
        "halo":40,
        "halomax":40,
        "power":"fire",
        "powerattack":2,
        "weakness":"ice",
        "position":{
            "world":"",
            "region":"",
            "scene":"",
            "step":"s4"
        }
    },
    "donna":{
        "name":"Donna",
        "halo":40,
        "halomax":40,
        "power":"shadows",
        "powerattack":2,
        "weakness":"thunder",
        "position":{
            "world":"",
            "region":"",
            "scene":"",
            "step":"s5"
        }
    },
    "molly":{
        "name":"Molly",
        "halo":40,
        "halomax":40,
        "power":"thunder",
        "powerattack":2,
        "weakness":"shadows",
        "position":{
            "world":"",
            "region":"",
            "scene":"",
            "step":"s6"
        }
    },
    "shiny":{
        "name":"Shiny",
        "halo":40,
        "halomax":40,
        "power":"shadows",
        "powerattack":2,
        "weakness":"thunder",
        "position":{
            "world":"",
            "region":"",
            "scene":"",
            "step":"s7"
        }
    } 
}
//console.log("heroes");
//console.log(heroes);